# Defaults for all jobs

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: aureliaeffect/circleci-v2:latest

# Variables
var_1: &cache_key tghtghtghtg-{{ .Branch }}-{{ checksum "package-lock.json" }}

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Publish nightly release
          command: |
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
            npm ci
            npm run bootstrap
            npm run build
            npm run publish:nightly


