# Defaults for all jobs

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: aureliaeffect/circleci-v2:latest

# Variables
var_1: &cache_key tghtghtghtg-{{ .Branch }}-{{ checksum "package-lock.json" }}

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/.npmrc
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/repo/.npmrc
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/repo/packages/.npmrc
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/repo/packages/pkg1/.npmrc
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/repo/packages/pkg2/.npmrc
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/repo/packages/pkg3/.npmrc
      - run:
          name: Publish nightly release
          command: |
            npm ci
            npm run bootstrap
            npm run build
            npm run publish:nightly


